/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CloudSimCost */

#ifndef _Included_CloudSimCost
#define _Included_CloudSimCost
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CloudSimCost
 * Method:    segmented_sort
 * Signature: ([F[I[III)V
 */
JNIEXPORT void JNICALL Java_CloudSimCost_segmented_1sort
  (JNIEnv *, jobject, jfloatArray, jintArray, jintArray, jint, jint);

/*
 * Class:     CloudSimCost
 * Method:    segmented_sort_desc
 * Signature: ([F[I[III)V
 */
JNIEXPORT void JNICALL Java_CloudSimCost_segmented_1sort_1desc
  (JNIEnv *, jobject, jfloatArray, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
