/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MinSortExample1 */

#ifndef _Included_MinSortExample1
#define _Included_MinSortExample1
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MinSortExample1
 * Method:    segmented_sort
 * Signature: ([F[I[III)V
 */
JNIEXPORT void JNICALL Java_MinSortExample1_segmented_1sort
  (JNIEnv *, jobject, jfloatArray, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
