/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MinSortCloudSim */

#ifndef _Included_MinSortCloudSim
#define _Included_MinSortCloudSim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MinSortCloudSim
 * Method:    segmented_sort
 * Signature: ([F[I[III)V
 */
JNIEXPORT void JNICALL Java_MinSortCloudSim_segmented_1sort
  (JNIEnv *, jobject, jfloatArray, jintArray, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
